
Due to MODULEPATH changes, the following have been reloaded:
  1) openmpi/2.1.1


Due to MODULEPATH changes, the following have been reloaded:
  1) openmpi/2.1.1

The following have been reloaded with a version change:
  1) cuda/10.0.130 => cuda/8.0.44

Start Time: Sun Jun  7 16:48:43 PDT 2020
max_size of vocab was specified as 50000; we now have 50000 words. Stopping reading.
Finished constructing vocabulary of 50000 total words. Last word added: pathogens
Dump hyper-parameters to models/train_1591573829/params_1591573829.json.
cuda:0
start training.
Train steps 200, seconds for 200 batch: 86.62 , loss: 4.694361, reward: 0.000000, elapse: 1.0m 27s, remain: 179.0m 1s
Train steps 400, seconds for 200 batch: 85.48 , loss: 4.414208, reward: 0.000000, elapse: 2.0m 53s, remain: 176.0m 24s
/project/6025349/vincenth/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/project/6025349/vincenth/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/project/6025349/vincenth/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/project/6025349/vincenth/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/project/6025349/vincenth/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/project/6025349/vincenth/.venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 600, seconds for 200 batch: 86.52 , loss: 4.234053, reward: 0.000000, elapse: 4.0m 19s, remain: 175.0m 18s
Train steps 800, seconds for 200 batch: 86.02 , loss: 4.096592, reward: 0.000000, elapse: 5.0m 45s, remain: 173.0m 47s
Train steps 1000, seconds for 200 batch: 85.45 , loss: 4.007414, reward: 0.000000, elapse: 7.0m 11s, remain: 172.0m 3s
Train steps 1200, seconds for 200 batch: 87.05 , loss: 3.931813, reward: 0.000000, elapse: 8.0m 38s, remain: 170.0m 58s
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 1400, seconds for 200 batch: 85.96 , loss: 3.865920, reward: 0.000000, elapse: 10.0m 4s, remain: 169.0m 28s
Train steps 1600, seconds for 200 batch: 85.58 , loss: 3.810538, reward: 0.000000, elapse: 11.0m 29s, remain: 167.0m 53s
Train steps 1800, seconds for 200 batch: 86.17 , loss: 3.763530, reward: 0.000000, elapse: 12.0m 55s, remain: 166.0m 28s
Train steps 2000, seconds for 200 batch: 86.16 , loss: 3.722519, reward: 0.000000, elapse: 14.0m 22s, remain: 165.0m 3s
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 2200, seconds for 200 batch: 87.33 , loss: 3.680317, reward: 0.000000, elapse: 15.0m 49s, remain: 163.0m 49s
Train steps 2400, seconds for 200 batch: 86.09 , loss: 3.645390, reward: 0.000000, elapse: 17.0m 15s, remain: 162.0m 22s
Train steps 2600, seconds for 200 batch: 86.84 , loss: 3.613018, reward: 0.000000, elapse: 18.0m 42s, remain: 161.0m 1s
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 2800, seconds for 200 batch: 86.17 , loss: 3.582852, reward: 0.000000, elapse: 20.0m 8s, remain: 159.0m 34s
Train steps 3000, seconds for 200 batch: 86.18 , loss: 3.551805, reward: 0.000000, elapse: 21.0m 34s, remain: 158.0m 7s
Train steps 3200, seconds for 200 batch: 86.34 , loss: 3.524568, reward: 0.000000, elapse: 23.0m 1s, remain: 156.0m 42s
Train steps 3400, seconds for 200 batch: 85.99 , loss: 3.498574, reward: 0.000000, elapse: 24.0m 27s, remain: 155.0m 14s
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 3600, seconds for 200 batch: 86.05 , loss: 3.471047, reward: 0.000000, elapse: 25.0m 53s, remain: 153.0m 47s
Train steps 3800, seconds for 200 batch: 86.34 , loss: 3.445674, reward: 0.000000, elapse: 27.0m 19s, remain: 152.0m 21s
Train steps 4000, seconds for 200 batch: 85.86 , loss: 3.421365, reward: 0.000000, elapse: 28.0m 45s, remain: 150.0m 53s
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 4200, seconds for 200 batch: 86.53 , loss: 3.397039, reward: 0.000000, elapse: 30.0m 11s, remain: 149.0m 28s
Train steps 4400, seconds for 200 batch: 86.06 , loss: 3.372567, reward: 0.000000, elapse: 31.0m 37s, remain: 148.0m 1s
Train steps 4600, seconds for 200 batch: 85.94 , loss: 3.349181, reward: 0.000000, elapse: 33.0m 3s, remain: 146.0m 34s
Train steps 4800, seconds for 200 batch: 86.05 , loss: 3.325945, reward: 0.000000, elapse: 34.0m 29s, remain: 145.0m 7s
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 5000, seconds for 200 batch: 85.95 , loss: 3.301423, reward: 0.000000, elapse: 35.0m 55s, remain: 143.0m 40s
Train steps 5200, seconds for 200 batch: 86.35 , loss: 3.277591, reward: 0.000000, elapse: 37.0m 22s, remain: 142.0m 15s
Train steps 5400, seconds for 200 batch: 85.96 , loss: 3.255545, reward: 0.000000, elapse: 38.0m 48s, remain: 140.0m 47s
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 5600, seconds for 200 batch: 86.04 , loss: 3.233219, reward: 0.000000, elapse: 40.0m 14s, remain: 139.0m 21s
Train steps 5800, seconds for 200 batch: 85.97 , loss: 3.209204, reward: 0.000000, elapse: 41.0m 40s, remain: 137.0m 54s
Train steps 6000, seconds for 200 batch: 85.31 , loss: 3.186736, reward: 0.000000, elapse: 43.0m 5s, remain: 136.0m 25s
Train steps 6200, seconds for 200 batch: 85.86 , loss: 3.165039, reward: 0.000000, elapse: 44.0m 31s, remain: 134.0m 58s
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 6400, seconds for 200 batch: 85.28 , loss: 3.142702, reward: 0.000000, elapse: 45.0m 56s, remain: 133.0m 29s
Train steps 6600, seconds for 200 batch: 85.23 , loss: 3.119741, reward: 0.000000, elapse: 47.0m 21s, remain: 132.0m 1s
Train steps 6800, seconds for 200 batch: 85.32 , loss: 3.097872, reward: 0.000000, elapse: 48.0m 47s, remain: 130.0m 33s
Train steps 7000, seconds for 200 batch: 85.26 , loss: 3.076485, reward: 0.000000, elapse: 50.0m 12s, remain: 129.0m 4s
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 7200, seconds for 200 batch: 86.19 , loss: 3.053980, reward: 0.000000, elapse: 51.0m 38s, remain: 127.0m 39s
Train steps 7400, seconds for 200 batch: 85.28 , loss: 3.032494, reward: 0.000000, elapse: 53.0m 3s, remain: 126.0m 11s
Train steps 7600, seconds for 200 batch: 85.49 , loss: 3.011969, reward: 0.000000, elapse: 54.0m 29s, remain: 124.0m 44s
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 7800, seconds for 200 batch: 85.38 , loss: 2.990915, reward: 0.000000, elapse: 55.0m 54s, remain: 123.0m 16s
Train steps 8000, seconds for 200 batch: 85.30 , loss: 2.969769, reward: 0.000000, elapse: 57.0m 20s, remain: 121.0m 49s
Train steps 8200, seconds for 200 batch: 85.97 , loss: 2.949113, reward: 0.000000, elapse: 58.0m 46s, remain: 120.0m 23s
Train steps 8400, seconds for 200 batch: 85.64 , loss: 2.928689, reward: 0.000000, elapse: 60.0m 11s, remain: 118.0m 56s
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 8600, seconds for 200 batch: 85.37 , loss: 2.907976, reward: 0.000000, elapse: 61.0m 37s, remain: 117.0m 29s
Train steps 8800, seconds for 200 batch: 85.24 , loss: 2.887954, reward: 0.000000, elapse: 63.0m 2s, remain: 116.0m 2s
Train steps 9000, seconds for 200 batch: 87.05 , loss: 2.867988, reward: 0.000000, elapse: 64.0m 29s, remain: 114.0m 38s
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 9200, seconds for 200 batch: 87.87 , loss: 2.848304, reward: 0.000000, elapse: 65.0m 57s, remain: 113.0m 15s
Train steps 9400, seconds for 200 batch: 87.37 , loss: 2.828725, reward: 0.000000, elapse: 67.0m 24s, remain: 111.0m 51s
Train steps 9600, seconds for 200 batch: 87.21 , loss: 2.809473, reward: 0.000000, elapse: 68.0m 51s, remain: 110.0m 27s
Train steps 9800, seconds for 200 batch: 87.35 , loss: 2.790604, reward: 0.000000, elapse: 70.0m 19s, remain: 109.0m 3s
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 10000, seconds for 200 batch: 87.21 , loss: 2.771763, reward: 0.000000, elapse: 71.0m 46s, remain: 107.0m 39s
Train steps 10200, seconds for 200 batch: 87.67 , loss: 2.753189, reward: 0.000000, elapse: 73.0m 14s, remain: 106.0m 15s
Train steps 10400, seconds for 200 batch: 87.26 , loss: 2.734815, reward: 0.000000, elapse: 74.0m 41s, remain: 104.0m 50s
Exception in thread Thread-18:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 10600, seconds for 200 batch: 87.40 , loss: 2.716950, reward: 0.000000, elapse: 76.0m 8s, remain: 103.0m 26s
Train steps 10800, seconds for 200 batch: 87.22 , loss: 2.698965, reward: 0.000000, elapse: 77.0m 36s, remain: 102.0m 1s
Train steps 11000, seconds for 200 batch: 87.37 , loss: 2.681104, reward: 0.000000, elapse: 79.0m 3s, remain: 100.0m 36s
Train steps 11200, seconds for 200 batch: 87.85 , loss: 2.663901, reward: 0.000000, elapse: 80.0m 31s, remain: 99.0m 12s
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 11400, seconds for 200 batch: 87.32 , loss: 2.646718, reward: 0.000000, elapse: 81.0m 58s, remain: 97.0m 47s
Train steps 11600, seconds for 200 batch: 87.37 , loss: 2.629657, reward: 0.000000, elapse: 83.0m 25s, remain: 96.0m 22s
Train steps 11800, seconds for 200 batch: 87.41 , loss: 2.613265, reward: 0.000000, elapse: 84.0m 53s, remain: 94.0m 57s
Train steps 12000, seconds for 200 batch: 87.29 , loss: 2.597051, reward: 0.000000, elapse: 86.0m 20s, remain: 93.0m 32s
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 12200, seconds for 200 batch: 88.34 , loss: 2.580494, reward: 0.000000, elapse: 87.0m 48s, remain: 92.0m 8s
Train steps 12400, seconds for 200 batch: 87.25 , loss: 2.564169, reward: 0.000000, elapse: 89.0m 16s, remain: 90.0m 42s
Train steps 12600, seconds for 200 batch: 87.28 , loss: 2.548336, reward: 0.000000, elapse: 90.0m 43s, remain: 89.0m 17s
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 12800, seconds for 200 batch: 87.47 , loss: 2.532634, reward: 0.000000, elapse: 92.0m 10s, remain: 87.0m 51s
Train steps 13000, seconds for 200 batch: 87.33 , loss: 2.516963, reward: 0.000000, elapse: 93.0m 38s, remain: 86.0m 26s
Train steps 13200, seconds for 200 batch: 87.87 , loss: 2.501665, reward: 0.000000, elapse: 95.0m 6s, remain: 85.0m 1s
Train steps 13400, seconds for 200 batch: 87.31 , loss: 2.486645, reward: 0.000000, elapse: 96.0m 33s, remain: 83.0m 35s
Exception in thread Thread-22:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 13600, seconds for 200 batch: 87.41 , loss: 2.471606, reward: 0.000000, elapse: 97.0m 60s, remain: 82.0m 9s
Train steps 13800, seconds for 200 batch: 87.33 , loss: 2.456811, reward: 0.000000, elapse: 99.0m 28s, remain: 80.0m 43s
Train steps 14000, seconds for 200 batch: 87.23 , loss: 2.442208, reward: 0.000000, elapse: 100.0m 55s, remain: 79.0m 18s
Train steps 14200, seconds for 200 batch: 87.20 , loss: 2.427890, reward: 0.000000, elapse: 102.0m 22s, remain: 77.0m 52s
Exception in thread Thread-23:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 14400, seconds for 200 batch: 88.03 , loss: 2.413677, reward: 0.000000, elapse: 103.0m 50s, remain: 76.0m 26s
Train steps 14600, seconds for 200 batch: 87.34 , loss: 2.399476, reward: 0.000000, elapse: 105.0m 18s, remain: 74.0m 60s
Train steps 14800, seconds for 200 batch: 87.23 , loss: 2.385664, reward: 0.000000, elapse: 106.0m 45s, remain: 73.0m 34s
Exception in thread Thread-24:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 15000, seconds for 200 batch: 87.46 , loss: 2.372028, reward: 0.000000, elapse: 108.0m 12s, remain: 72.0m 8s
Train steps 15200, seconds for 200 batch: 87.69 , loss: 2.358412, reward: 0.000000, elapse: 109.0m 40s, remain: 70.0m 42s
Train steps 15400, seconds for 200 batch: 87.25 , loss: 2.344980, reward: 0.000000, elapse: 111.0m 7s, remain: 69.0m 16s
Train steps 15600, seconds for 200 batch: 87.14 , loss: 2.331846, reward: 0.000000, elapse: 112.0m 34s, remain: 67.0m 50s
Exception in thread Thread-25:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 15800, seconds for 200 batch: 87.68 , loss: 2.318705, reward: 0.000000, elapse: 114.0m 2s, remain: 66.0m 24s
Train steps 16000, seconds for 200 batch: 87.30 , loss: 2.305700, reward: 0.000000, elapse: 115.0m 29s, remain: 64.0m 58s
Train steps 16200, seconds for 200 batch: 87.66 , loss: 2.292980, reward: 0.000000, elapse: 116.0m 57s, remain: 63.0m 32s
Exception in thread Thread-26:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 16400, seconds for 200 batch: 87.39 , loss: 2.280465, reward: 0.000000, elapse: 118.0m 24s, remain: 62.0m 6s
Train steps 16600, seconds for 200 batch: 87.45 , loss: 2.268068, reward: 0.000000, elapse: 119.0m 52s, remain: 60.0m 39s
Train steps 16800, seconds for 200 batch: 87.30 , loss: 2.255821, reward: 0.000000, elapse: 121.0m 19s, remain: 59.0m 13s
Train steps 17000, seconds for 200 batch: 87.35 , loss: 2.243845, reward: 0.000000, elapse: 122.0m 47s, remain: 57.0m 47s
Exception in thread Thread-27:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 17200, seconds for 200 batch: 87.80 , loss: 2.231915, reward: 0.000000, elapse: 124.0m 14s, remain: 56.0m 21s
Train steps 17400, seconds for 200 batch: 87.67 , loss: 2.220097, reward: 0.000000, elapse: 125.0m 42s, remain: 54.0m 54s
Train steps 17600, seconds for 200 batch: 87.26 , loss: 2.208484, reward: 0.000000, elapse: 127.0m 9s, remain: 53.0m 28s
Train steps 17800, seconds for 200 batch: 86.68 , loss: 2.197030, reward: 0.000000, elapse: 128.0m 36s, remain: 52.0m 1s
Exception in thread Thread-28:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 18000, seconds for 200 batch: 88.21 , loss: 2.185550, reward: 0.000000, elapse: 130.0m 4s, remain: 50.0m 35s
Train steps 18200, seconds for 200 batch: 87.63 , loss: 2.174301, reward: 0.000000, elapse: 131.0m 32s, remain: 49.0m 9s
Train steps 18400, seconds for 200 batch: 87.46 , loss: 2.163263, reward: 0.000000, elapse: 132.0m 59s, remain: 47.0m 42s
Exception in thread Thread-29:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 18600, seconds for 200 batch: 87.37 , loss: 2.152360, reward: 0.000000, elapse: 134.0m 27s, remain: 46.0m 16s
Train steps 18800, seconds for 200 batch: 87.50 , loss: 2.141537, reward: 0.000000, elapse: 135.0m 54s, remain: 44.0m 49s
Train steps 19000, seconds for 200 batch: 87.35 , loss: 2.130882, reward: 0.000000, elapse: 137.0m 22s, remain: 43.0m 23s
Train steps 19200, seconds for 200 batch: 87.66 , loss: 2.120441, reward: 0.000000, elapse: 138.0m 49s, remain: 41.0m 56s
Exception in thread Thread-30:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 19400, seconds for 200 batch: 89.05 , loss: 2.109992, reward: 0.000000, elapse: 140.0m 18s, remain: 40.0m 30s
Train steps 19600, seconds for 200 batch: 87.30 , loss: 2.099746, reward: 0.000000, elapse: 141.0m 46s, remain: 39.0m 4s
Train steps 19800, seconds for 200 batch: 87.35 , loss: 2.089654, reward: 0.000000, elapse: 143.0m 13s, remain: 37.0m 37s
Exception in thread Thread-31:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 20000, seconds for 200 batch: 87.48 , loss: 2.079682, reward: 0.000000, elapse: 144.0m 40s, remain: 36.0m 10s
Train steps 20200, seconds for 200 batch: 87.82 , loss: 2.069865, reward: 0.000000, elapse: 146.0m 8s, remain: 34.0m 44s
Train steps 20400, seconds for 200 batch: 87.24 , loss: 2.060120, reward: 0.000000, elapse: 147.0m 35s, remain: 33.0m 17s
Train steps 20600, seconds for 200 batch: 87.41 , loss: 2.050488, reward: 0.000000, elapse: 149.0m 3s, remain: 31.0m 51s
Exception in thread Thread-32:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 20800, seconds for 200 batch: 87.43 , loss: 2.040962, reward: 0.000000, elapse: 150.0m 30s, remain: 30.0m 24s
Train steps 21000, seconds for 200 batch: 87.38 , loss: 2.031563, reward: 0.000000, elapse: 151.0m 58s, remain: 28.0m 57s
Train steps 21200, seconds for 200 batch: 87.70 , loss: 2.022209, reward: 0.000000, elapse: 153.0m 25s, remain: 27.0m 30s
Train steps 21400, seconds for 200 batch: 86.56 , loss: 2.012960, reward: 0.000000, elapse: 154.0m 52s, remain: 26.0m 4s
Exception in thread Thread-33:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 21600, seconds for 200 batch: 88.31 , loss: 2.003821, reward: 0.000000, elapse: 156.0m 20s, remain: 24.0m 37s
Train steps 21800, seconds for 200 batch: 87.31 , loss: 1.994828, reward: 0.000000, elapse: 157.0m 48s, remain: 23.0m 10s
Train steps 22000, seconds for 200 batch: 87.38 , loss: 1.985818, reward: 0.000000, elapse: 159.0m 15s, remain: 21.0m 43s
Exception in thread Thread-34:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 22200, seconds for 200 batch: 87.96 , loss: 1.976896, reward: 0.000000, elapse: 160.0m 43s, remain: 20.0m 17s
Train steps 22400, seconds for 200 batch: 87.27 , loss: 1.968145, reward: 0.000000, elapse: 162.0m 10s, remain: 18.0m 50s
Train steps 22600, seconds for 200 batch: 87.41 , loss: 1.959476, reward: 0.000000, elapse: 163.0m 38s, remain: 17.0m 23s
Exception in thread Thread-35:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 22800, seconds for 200 batch: 87.42 , loss: 1.950927, reward: 0.000000, elapse: 165.0m 5s, remain: 15.0m 56s
Train steps 23000, seconds for 200 batch: 87.45 , loss: 1.942423, reward: 0.000000, elapse: 166.0m 32s, remain: 14.0m 29s
Train steps 23200, seconds for 200 batch: 87.65 , loss: 1.933992, reward: 0.000000, elapse: 167.0m 60s, remain: 13.0m 3s
Train steps 23400, seconds for 200 batch: 87.49 , loss: 1.925788, reward: 0.000000, elapse: 169.0m 28s, remain: 11.0m 36s
Exception in thread Thread-36:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 23600, seconds for 200 batch: 87.37 , loss: 1.917624, reward: 0.000000, elapse: 170.0m 55s, remain: 10.0m 9s
Train steps 23800, seconds for 200 batch: 87.32 , loss: 1.909501, reward: 0.000000, elapse: 172.0m 22s, remain: 8.0m 42s
Train steps 24000, seconds for 200 batch: 87.17 , loss: 1.901505, reward: 0.000000, elapse: 173.0m 49s, remain: 7.0m 15s
Train steps 24200, seconds for 200 batch: 87.78 , loss: 1.893582, reward: 0.000000, elapse: 175.0m 17s, remain: 5.0m 48s
Exception in thread Thread-37:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 24400, seconds for 200 batch: 87.38 , loss: 1.885816, reward: 0.000000, elapse: 176.0m 45s, remain: 4.0m 21s
Train steps 24600, seconds for 200 batch: 87.31 , loss: 1.878078, reward: 0.000000, elapse: 178.0m 12s, remain: 2.0m 54s
Train steps 24800, seconds for 200 batch: 87.20 , loss: 1.870463, reward: 0.000000, elapse: 179.0m 39s, remain: 1.0m 27s
Exception in thread Thread-38:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 213, in fill_example_queue
    input_gen)  # read the next example from file. article and abstract are both strings.
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/batcher.py", line 280, in text_generator
    e = next(example_generator)  # e is a tf.Example
  File "/project/6025349/vincenth/PRSummarizer/prsum/dataset/data.py", line 86, in example_generator
    for row in reader:
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte

ERROR:tensorflow:Found example queue thread dead. Restarting.
Train steps 25000, seconds for 200 batch: 87.41 , loss: 1.862870, reward: 0.000000, elapse: 181.0m 7s, remain: 0.0m 0s
end training.
Start Time: Sun Jun  7 16:48:43 PDT 2020
End Time: Sun Jun  7 19:51:49 PDT 2020
